POST http://localhost:8000/member-service/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "测试",
  "idCard": 440599203002299999,
  "type": 1
}

###

GET http://localhost:8000/member-service/passenger/query-list?page=2&size=5
Accept: application/json
token: {{token}}

###